In [5]:
import pandas, requests, bs4, lxml, plotly
print("Semua paket sudah tersedia ✓")

Semua paket sudah tersedia ✓

In [8]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import warnings; warnings.filterwarnings('ignore', category=FutureWarning)
url = ("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/netflix_data_webpage.html")
data = requests.get(url).text
soup = BeautifulSoup(data, 'html.parser')

Membaca tiap baris tabel dan menyusunnya menjadi DataFrame harga saham Netflix.

In [16]:
netflix_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Adj Close", "Volume"])

for row in soup.find("tbody").find_all("tr"):
    col = row.find_all("td")
    netflix_data = pd.concat([netflix_data, pd.DataFrame({
        "Date": [col[0].text],
        "Open": [col[1].text],
        "High": [col[2].text],
        "Low": [col[3].text],
        "Close": [col[4].text],
        "Adj Close": [col[5].text],
        "Volume": [col[6].text]
    })], ignore_index=True)

netflix_data.head()

           Date      Open      High       Low     Close Adj Close       Volume
0  Jan 01, 2021  3,270.00  3,363.89  3,086.00  3,206.20  3,206.20   71,528,900
1  Dec 01, 2020  3,188.50  3,350.65  3,072.82  3,256.93  3,256.93   77,556,200
2  Nov 01, 2020  3,061.74  3,366.80  2,950.12  3,168.04  3,168.04   90,810,500
3  Oct 01, 2020  3,208.00  3,496.24  3,019.00  3,036.15  3,036.15  116,226,100
4  Sep 01, 2020  3,489.58  3,552.25  2,871.00  3,148.73  3,148.73  115,899,300

Menggunakan versi read_html agar pandas otomatis mengidentifikasi tipe data dengan benar

In [11]:
from io import StringIO
read_html_pandas_data = pd.read_html(StringIO(str(soup)))
netflix_dataframe = read_html_pandas_data[0]
netflix_dataframe.head()

           Date    Open    High     Low  Close* Adj Close**     Volume
0  Jun 01, 2021  504.01  536.13  482.14  528.21      528.21   78560600
1  May 01, 2021  512.65  518.95  478.54  502.81      502.81   66927600
2  Apr 01, 2021  529.93  563.56  499.00  513.47      513.47  111573300
3  Mar 01, 2021  545.57  556.99  492.85  521.66      521.66   90183900
4  Feb 01, 2021  536.79  566.65  518.28  538.85      538.85   61902300

Membaca tiap baris tabel dan menyusunnya menjadi DataFrame harga saham Amazon

In [12]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/amazon_data_webpage.html"
data = requests.get(url).text
soup = BeautifulSoup(data, "html.parser")

In [13]:
amazon_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Volume"])

for row in soup.find("tbody").find_all("tr"):
    col = row.find_all("td")
    date      = col[0].text
    Open      = col[1].text
    high      = col[2].text
    low       = col[3].text
    close     = col[4].text
    adj_close = col[5].text
    volume    = col[6].text
    
    amazon_data = pd.concat([amazon_data, pd.DataFrame({"Date":[date], "Open":[Open], "High":[high], "Low":[low], "Close":[close], "Adj Close":[adj_close], "Volume":[volume]})], ignore_index=True)

In [14]:
df = amazon_data.head()
df

           Date      Open      High       Low     Close       Volume Adj Close
0  Jan 01, 2021  3,270.00  3,363.89  3,086.00  3,206.20   71,528,900  3,206.20
1  Dec 01, 2020  3,188.50  3,350.65  3,072.82  3,256.93   77,556,200  3,256.93
2  Nov 01, 2020  3,061.74  3,366.80  2,950.12  3,168.04   90,810,500  3,168.04
3  Oct 01, 2020  3,208.00  3,496.24  3,019.00  3,036.15  116,226,100  3,036.15
4  Sep 01, 2020  3,489.58  3,552.25  2,871.00  3,148.73  115,899,300  3,148.73

In [15]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')